spring:
  application:
    name: customer-service
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/zinebMachrouh/GringottsConfig.git
  datasource:
    url: jdbc:postgresql://localhost:5438/CustomerDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081