spring:
  application:
    name: gateway-service
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/zinebMachrouh/GringottsConfig.git
server:
    port: 9090