version: "3.7"
services:
  db:
    image: mysql:latest
    container_name: Account-DB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AccountDB
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
