server:
  port: 8087

spring:
    application:
        name: config-service
    cloud:
      config:
        server:
          git:
            clone-on-start: true
            uri: https://github.com/zinebMachrouh/GringottsConfig.git
